name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
    - uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
        path: dist/*

  deploy:
    needs: build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install twine
    - uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: wheel-*
        merge-multiple: true
    - name: Build sdist
      run: |
        python setup.py sdist
        dir -recurse dist
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
