name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*

  deploy:
    needs: build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install twine
    - uses: actions/download-artifact@v4.1.7
      with:
        path: artifacts
    - name: Build sdist
      run: |
        python setup.py sdist
        cp artifacts/artifact/* dist
        dir -recurse dist
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
